# Generated by Django 3.2 on 2021-05-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_police_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(choices=[('License', 'License'), ('Adhaar', 'Adhaar_card'), ('Pan', 'Pan_card')], max_length=255),
        ),
    ]
