# Generated by Django 3.2 on 2021-06-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='made_by',
        ),
    ]
