# Generated by Django 3.2 on 2021-06-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_transaction_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='made_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.userallowed'),
        ),
    ]
