# Generated by Django 3.2 on 2021-06-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210602_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='email',
        ),
        migrations.AddField(
            model_name='transaction',
            name='made_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.userallowed'),
        ),
    ]
