# Generated by Django 3.2 on 2021-06-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210602_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='made_by',
        ),
    ]
